name: recsys-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26
  - pandas=2.0
  - scipy=1.10
  - scikit-learn=1.3
  - scikit-surprise=1.1.3
  - matplotlib=3.7
  - seaborn=0.12
  - jupyterlab
  - ipykernel
  - black
  - isort
  - pre-commit
  - pytest
